#!/usr/bin/env python3
"""Create the Swift Propshaft-path table during the image build."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "reference" / "app" / "assets"
OUTPUT = ROOT / "Sources" / "CampfireCore" / "GeneratedAssetManifest.swift"

# Rust owns these rendered overrides; their digests come from its parity-tested Propshaft build.
OVERRIDES = {
    "flash.css": "/assets/flash-a561c1e5.css",
    "layout.css": "/assets/layout-ff6ddfc6.css",
    "sidebar.css": "/assets/sidebar-0be58db9.css",
}

paths = {}
for asset in sorted(ASSETS.rglob("*")) if ASSETS.exists() else []:
    if not asset.is_file() or asset.name.startswith("."):
        continue
    logical = asset.relative_to(ASSETS).as_posix()
    digest = hashlib.sha256(asset.read_bytes()).hexdigest()[:8]
    paths[logical] = f"/assets/{asset.stem}-{digest}{asset.suffix}"

# The Rails build manifest wins for compiled assets; Rust's render-owned paths win last.
rails_manifest = ROOT / "reference" / "public" / "assets" / ".manifest.json"
if rails_manifest.exists():
    for logical, entry in json.loads(rails_manifest.read_text()).items():
        digest_path = entry.get("digested_path") if isinstance(entry, dict) else entry
        if digest_path:
            paths[logical] = f"/assets/{digest_path.lstrip('/')}"
paths.update(OVERRIDES)

entries = ",\n".join(f"        {json.dumps(key)}: {json.dumps(value)}" for key, value in sorted(paths.items()))
OUTPUT.write_text(
    "// Generated by Scripts/generate-asset-manifest.py.\n"
    "enum GeneratedAssetManifest {\n"
    "    static let paths: [String: String] = [\n"
    f"{entries}\n"
    "    ]\n}\n"
)
