// Generated by Scripts/generate-asset-manifest.py.
enum GeneratedAssetManifest {
    static let paths: [String: String] = [
        "flash.css": "/assets/flash-a561c1e5.css",
        "layout.css": "/assets/layout-ff6ddfc6.css",
        "sidebar.css": "/assets/sidebar-0be58db9.css"
    ]
}
